# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
et:
  languageCode: et
  contentDir: content/et
  title: Vastsündinu fotograaf 
  params:
    description: Vastündinu fotograaf Tallinnas - Viktoria Iljin
  menu:
    main:
      - name: Minust
        url: '#about'
        weight: 40
      - name: Portfoolio 
        url: '#projects'
        weight: 10
      - name: Hinnakiri
        url: '#skills'
        weight: 20
      - name: Kontakt
        url: '#contact'
        weight: 50
      - name: Blogi
        url: '#featured'
        weight: 30
ru:
  languageCode: ru
  contentDir: content/ru
  title: Фотограф новорожденных
  params:
    description: Фотограф новорожденных в Таллинне - Виктория Ильин
  menu:  
    main:
      - name: Обо мне
        url: '#about'
        weight: 40
      - name: Портфолио 
        url: '#projects'
        weight: 10
      - name: Цены
        url: '#skills'
        weight: 20
      - name: Контакт
        url: '#contact'
        weight: 50
      - name: Блог
        url: '#featured'
        weight: 30
en:
  languageCode: en
  contentDir: content/en
  title: Newborn photographer
  params:
    description: Newborn photographer - Viktoria Iljin
  menu:
    main:
      - name: About me
        url: '#about'
        weight: 40
      - name: Portfolio
        url: '#projects'
        weight: 10
      - name: Prices
        url: '#skills'
        weight: 20
      - name: Contact
        url: '#contact'
        weight: 50
      - name: Blog
        url: '#featured'
        weight: 30

  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
